#!/usr/bin/env python3
"""Compile the Havok 2014 SDK headers with clang-cl (MSVC x64 ABI) and dump
exact record layouts for every reflected class, then parse to JSON.

Why this works where in-binary reflection mining failed: Bethesda ships no
offset-bearing havok reflection (see scripts/core/havok_mine.py), but the
SDK headers define the same classes, and clang's -fdump-record-layouts
makes the compiler compute the authoritative MSVC-ABI field offsets --
sidestepping all the template / SIMD-alignment / inheritance hand-math.

Pipeline:
  1. enumerate class names from the SDK's autogenerated *Classes.h
     registration lists (HK_CLASS / HK_ABSTRACT_CLASS macros)
  2. emit a TU that includes the module umbrellas and forces the full
     layout of each class via sizeof()
  3. compile; any class whose definition isn't transitively included shows
     up as an "incomplete type" error -- prune it and recompile until clean
     (auto-converges to the maximal compilable subset)
  4. -fdump-record-layouts -> parse_layouts.py -> JSON

clang-cl is used so the layout matches the game's MSVC build.  The SSE
intrinsics path is forced (-DHK_COMPILER_HAS_INTRINSICS_IA32) because Havok
2014 predates clang and routes it into its GCC branch, which fails to
enable x64 SSE -- the SSE path gives the 16-byte-aligned hkVector4 the game
uses, so offsets match.

Output: build/havok/havok_layouts.json  ({class: {size, align, vtable,
fields:[{offset,type,name}]}}).
"""
import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
CLCL = r"C:/Program Files/LLVM/bin/clang-cl.exe"
SDK = Path(r"C:/Development/higgs-master/Havok 2014 SDK/Source")
BUILD = REPO / "build" / "havok"

# Module umbrellas, by BASENAME (resolved via header_index, so the same
# list works whether physics lives under Physics2012/ (2014) or Physics/
# (6.6)).  Order doesn't matter; the compiler resolves includes.
UMBRELLA_NAMES = [
    "hkBase", "hkxScene", "hkpDynamics", "hkpCollide", "hkpUtilities",
    "hkpVehicle", "hkaAnimation", "hkaRagdoll", "hkpConstraint",
]
# Registration-list filename pattern; enumerate class names from any
# *Classes.h sitting in a Classes/ or Classlist/ directory.
ARCH = 'x64'
# Matches both the 2014 two-arg form HK_CLASS(EXPORT, Name) and the 6.6
# one-arg forms HK_CLASS(Name) / HK_ABSTRACT_CLASS(Name) / HK_STRUCT(Name).
CLASS_RE = re.compile(
    r'HK_(?:ABSTRACT_CLASS|CLASS|STRUCT)\s*\(\s*(?:[^,()]*,\s*)?'
    r'([A-Za-z_]\w*)\s*\)')
# anchored: capture only the offending name (not a "did you mean 'Y'" suffix)
PRUNE_RES = [
    re.compile(r"incomplete type '([A-Za-z_]\w*)'"),
    re.compile(r"unknown type name '([A-Za-z_]\w*)'"),
    re.compile(r"undeclared identifier '([A-Za-z_]\w*)'"),
    re.compile(r"unknown class name '([A-Za-z_]\w*)'"),
]

_HEADER_INDEX = None


def header_index():
    global _HEADER_INDEX
    if _HEADER_INDEX is None:
        _HEADER_INDEX = {}
        for p in SDK.rglob("*.h"):
            _HEADER_INDEX.setdefault(p.stem, p)
    return _HEADER_INDEX


def enumerate_classes():
    names = set()
    for f in SDK.rglob("*Classes.h"):
        parts = {p.lower() for p in f.parts}
        if 'classes' not in parts and 'classlist' not in parts:
            continue
        txt = f.read_text(errors='replace')
        for m in CLASS_RE.finditer(txt):
            names.add(m.group(1))
    return sorted(names)


def write_tu(path, classes, bad_includes):
    idx = header_index()
    incs = []
    for u in UMBRELLA_NAMES:
        h = idx.get(u)
        if h is not None:
            incs.append(h.relative_to(SDK).as_posix())
    # add each class's own <Class>.h header (maximizes definitions available)
    for c in classes:
        h = idx.get(c)
        if h is None:
            continue
        rel = h.relative_to(SDK).as_posix()
        if rel not in incs and rel not in bad_includes:
            incs.append(rel)
    with open(path, 'w') as fh:
        for inc in incs:
            fh.write('#include <%s>\n' % inc)
        fh.write('\ntemplate<class T> struct HkForce { char _c[sizeof(T)]; };\n')
        fh.write('int main(){\n')
        for c in classes:
            fh.write('  (void)sizeof(HkForce<%s>);\n' % c)
        fh.write('  return 0;\n}\n')
    return incs


def compile_tu(path, dump=False):
    # Build args in a fixed clean order (no index-insertion -- that split the
    # -I/<dir> pairs when -m32 was absent, breaking the x64 dump pass).
    args = [CLCL, "/std:c++14", "-fsyntax-only", "-W0"]
    if ARCH == 'x86':
        args.append("-m32")
    if dump:
        args += ["-Xclang", "-fdump-record-layouts"]
    # extra include dirs first (shim for legacy <typeinfo.h>/<new.h> that
    # pre-2010 Havok expects), then the SDK root.
    for inc in (os.environ.get('BGS_HAVOK_INC', '') or '').split(';'):
        if inc.strip():
            args += ["-I", inc.strip()]
    args += ["-I", str(SDK), "-DHK_COMPILER_HAS_INTRINSICS_IA32", str(path)]
    p = subprocess.run(args, capture_output=True, text=True)
    return p.returncode, p.stdout, p.stderr


def main():
    global SDK, ARCH
    ap = argparse.ArgumentParser()
    ap.add_argument('--max-iters', type=int, default=40)
    ap.add_argument('--sdk', default=str(SDK),
                    help="Havok SDK Source root (default: 2014 SDK)")
    ap.add_argument('--arch', choices=['x64', 'x86'], default='x64')
    ap.add_argument('--out', default='havok_layouts.json',
                    help="output JSON filename under scripts/havok/refs/")
    args = ap.parse_args()
    SDK = Path(args.sdk)
    ARCH = args.arch
    BUILD.mkdir(parents=True, exist_ok=True)

    classes = list(enumerate_classes())
    print("enumerated %d reflected classes from registration lists" % len(classes))
    tu = BUILD / "_all.cpp"
    incfrom = re.compile(r'_all\.cpp[\(:](\d+)')

    dropped = []
    bad_includes = set()
    incs = []
    for it in range(args.max_iters):
        incs = write_tu(tu, classes, bad_includes)
        rc, out, err = compile_tu(tu, dump=False)
        if rc == 0:
            print("compiled clean after %d iters (%d classes, %d dropped, "
                  "%d bad includes)" % (it, len(classes), len(dropped),
                                        len(bad_includes)))
            break
        # 1. prune classes whose forcer line (_all.cpp) errored
        bad_cls = set()
        for line in err.splitlines():
            if '_all.cpp' not in line or 'error:' not in line:
                continue
            for rx in PRUNE_RES:
                m = rx.search(line)
                if m:
                    bad_cls.add(m.group(1))
        bad_cls &= set(classes)
        if bad_cls:
            for b in bad_cls:
                classes.remove(b)
                dropped.append(b)
            print("  iter %d: pruned %d classes (%d remain)"
                  % (it, len(bad_cls), len(classes)))
            continue
        # 2. otherwise a header errored internally -> drop the umbrella/class
        #    include on the mapped _all.cpp line
        droppable = None
        for line in err.splitlines():
            if 'error:' not in line:
                continue
            # find the include-trace _all.cpp line numbers
        for line in err.splitlines():
            m = incfrom.search(line)
            if m:
                ln = int(m.group(1)) - 1
                if 0 <= ln < len(incs) and incs[ln] not in bad_includes:
                    droppable = incs[ln]
                    break
        if droppable:
            bad_includes.add(droppable)
            print("  iter %d: dropped bad include %s" % (it, droppable))
            continue
        print("compile failed, nothing prunable; first errors:")
        for l in err.splitlines():
            if 'error:' in l:
                print("   " + l)
        sys.exit(1)
    else:
        print("did not converge in %d iters" % args.max_iters)
        sys.exit(1)

    # final compile WITH layout dump
    rc, out, err = compile_tu(tu, dump=True)
    dump_path = BUILD / "_all.layouts.txt"
    dump_path.write_text(out, errors='replace')
    nrec = out.count('Dumping AST Record Layout')
    print("dumped %d records -> %s" % (nrec, dump_path))

    # parse to JSON
    sys.path.insert(0, str(Path(__file__).parent))
    import parse_layouts
    recs = parse_layouts.parse(out)
    recs = {k: v for k, v in recs.items() if k.startswith(('hk', 'bhk'))}
    import json
    refs = Path(__file__).resolve().parent / "refs"
    refs.mkdir(exist_ok=True)
    outjson = refs / args.out
    json.dump(recs, open(outjson, 'w'), indent=1)
    (refs / (args.out.replace('.json', '') + "_dropped.txt")).write_text(
        '\n'.join(sorted(dropped)))
    print("parsed %d hk* records -> %s" % (len(recs), outjson))
    withf = sum(1 for v in recs.values() if v['fields'])
    print("  %d have >=1 field; %d are polymorphic" %
          (withf, sum(1 for v in recs.values() if v['vtable'])))


if __name__ == '__main__':
    main()
