#!/usr/bin/env python3
"""Compile the Havok 2014 SDK headers with clang-cl (MSVC x64 ABI) and dump
exact record layouts for every reflected class, then parse to JSON.

Why this works where in-binary reflection mining failed: Bethesda ships no
offset-bearing havok reflection (see scripts/core/havok_mine.py), but the
SDK headers define the same classes, and clang's -fdump-record-layouts
makes the compiler compute the authoritative MSVC-ABI field offsets --
sidestepping all the template / SIMD-alignment / inheritance hand-math.

Pipeline:
  1. enumerate class names from the SDK's autogenerated *Classes.h
     registration lists (HK_CLASS / HK_ABSTRACT_CLASS macros)
  2. emit a TU that includes the module umbrellas and forces the full
     layout of each class via sizeof()
  3. compile; any class whose definition isn't transitively included shows
     up as an "incomplete type" error -- prune it and recompile until clean
     (auto-converges to the maximal compilable subset)
  4. -fdump-record-layouts -> parse_layouts.py -> JSON

clang-cl is used so the layout matches the game's MSVC build.  The SSE
intrinsics path is forced (-DHK_COMPILER_HAS_INTRINSICS_IA32) because Havok
2014 predates clang and routes it into its GCC branch, which fails to
enable x64 SSE -- the SSE path gives the 16-byte-aligned hkVector4 the game
uses, so offsets match.

Output: build/havok/havok_layouts.json  ({class: {size, align, vtable,
fields:[{offset,type,name}]}}).
"""
import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
CLCL = r"C:/Program Files/LLVM/bin/clang-cl.exe"
SDK = Path(r"C:/Development/higgs-master/Havok 2014 SDK/Source")
BUILD = REPO / "build" / "havok"

# Module umbrellas to include (pull in most class definitions).  Order
# matters only for readability; the compiler resolves includes.
UMBRELLAS = [
    "Common/Base/hkBase.h",
    "Common/SceneData/Scene/hkxScene.h",
    "Physics2012/Dynamics/hkpDynamics.h",
    "Physics2012/Collide/hkpCollide.h",
    "Physics2012/Utilities/hkpUtilities.h",
    "Physics2012/Vehicle/hkpVehicle.h",
    "Animation/Animation/hkaAnimation.h",
    "Animation/Ragdoll/hkaRagdoll.h",
]
# Registration lists to enumerate class names from (glob under SDK).
CLASSLIST_GLOBS = [
    "Common/Serialize/Classlist/*Classes.h",
    "Physics2012/*/Classes/*Classes.h",
    "Physics/*/Classes/*Classes.h",
    "Animation/*/Classes/*Classes.h",
]
CLASS_RE = re.compile(r'HK_(?:ABSTRACT_)?CLASS\s*\(\s*[^,]*,\s*([A-Za-z_]\w*)\s*\)')
# anchored: capture only the offending name (not a "did you mean 'Y'" suffix)
PRUNE_RES = [
    re.compile(r"incomplete type '([A-Za-z_]\w*)'"),
    re.compile(r"unknown type name '([A-Za-z_]\w*)'"),
    re.compile(r"undeclared identifier '([A-Za-z_]\w*)'"),
    re.compile(r"unknown class name '([A-Za-z_]\w*)'"),
]

_HEADER_INDEX = None


def header_index():
    global _HEADER_INDEX
    if _HEADER_INDEX is None:
        _HEADER_INDEX = {}
        for p in SDK.rglob("*.h"):
            _HEADER_INDEX.setdefault(p.stem, p)
    return _HEADER_INDEX


def enumerate_classes():
    names = set()
    for g in CLASSLIST_GLOBS:
        for f in SDK.glob(g):
            txt = f.read_text(errors='replace')
            for m in CLASS_RE.finditer(txt):
                names.add(m.group(1))
    return sorted(names)


def write_tu(path, classes, bad_includes):
    idx = header_index()
    incs = []
    for u in UMBRELLAS:
        if (SDK / u).is_file():
            incs.append(u.replace('\\', '/'))
    # add each class's own <Class>.h header (maximizes definitions available)
    for c in classes:
        h = idx.get(c)
        if h is None:
            continue
        rel = h.relative_to(SDK).as_posix()
        if rel not in incs and rel not in bad_includes:
            incs.append(rel)
    with open(path, 'w') as fh:
        for inc in incs:
            fh.write('#include <%s>\n' % inc)
        fh.write('\ntemplate<class T> struct HkForce { char _c[sizeof(T)]; };\n')
        fh.write('int main(){\n')
        for c in classes:
            fh.write('  (void)sizeof(HkForce<%s>);\n' % c)
        fh.write('  return 0;\n}\n')
    return incs


def compile_tu(path, dump=False):
    args = [CLCL, "/std:c++14", "-fsyntax-only", "-W0",
            "-I", str(SDK), "-DHK_COMPILER_HAS_INTRINSICS_IA32", str(path)]
    if dump:
        args[2:2] = ["-Xclang", "-fdump-record-layouts"]
    p = subprocess.run(args, capture_output=True, text=True)
    return p.returncode, p.stdout, p.stderr


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--max-iters', type=int, default=40)
    args = ap.parse_args()
    BUILD.mkdir(parents=True, exist_ok=True)

    classes = list(enumerate_classes())
    print("enumerated %d reflected classes from registration lists" % len(classes))
    tu = BUILD / "_all.cpp"
    incfrom = re.compile(r'_all\.cpp[\(:](\d+)')

    dropped = []
    bad_includes = set()
    incs = []
    for it in range(args.max_iters):
        incs = write_tu(tu, classes, bad_includes)
        rc, out, err = compile_tu(tu, dump=False)
        if rc == 0:
            print("compiled clean after %d iters (%d classes, %d dropped, "
                  "%d bad includes)" % (it, len(classes), len(dropped),
                                        len(bad_includes)))
            break
        # 1. prune classes whose forcer line (_all.cpp) errored
        bad_cls = set()
        for line in err.splitlines():
            if '_all.cpp' not in line or 'error:' not in line:
                continue
            for rx in PRUNE_RES:
                m = rx.search(line)
                if m:
                    bad_cls.add(m.group(1))
        bad_cls &= set(classes)
        if bad_cls:
            for b in bad_cls:
                classes.remove(b)
                dropped.append(b)
            print("  iter %d: pruned %d classes (%d remain)"
                  % (it, len(bad_cls), len(classes)))
            continue
        # 2. otherwise a header errored internally -> drop the umbrella/class
        #    include on the mapped _all.cpp line
        droppable = None
        for line in err.splitlines():
            if 'error:' not in line:
                continue
            # find the include-trace _all.cpp line numbers
        for line in err.splitlines():
            m = incfrom.search(line)
            if m:
                ln = int(m.group(1)) - 1
                if 0 <= ln < len(incs) and incs[ln] not in bad_includes:
                    droppable = incs[ln]
                    break
        if droppable:
            bad_includes.add(droppable)
            print("  iter %d: dropped bad include %s" % (it, droppable))
            continue
        print("compile failed, nothing prunable; first errors:")
        for l in err.splitlines():
            if 'error:' in l:
                print("   " + l)
        sys.exit(1)
    else:
        print("did not converge in %d iters" % args.max_iters)
        sys.exit(1)

    # final compile WITH layout dump
    rc, out, err = compile_tu(tu, dump=True)
    dump_path = BUILD / "_all.layouts.txt"
    dump_path.write_text(out, errors='replace')
    nrec = out.count('Dumping AST Record Layout')
    print("dumped %d records -> %s" % (nrec, dump_path))

    # parse to JSON
    sys.path.insert(0, str(Path(__file__).parent))
    import parse_layouts
    recs = parse_layouts.parse(out)
    recs = {k: v for k, v in recs.items() if k.startswith(('hk', 'bhk'))}
    import json
    refs = Path(__file__).resolve().parent / "refs"
    refs.mkdir(exist_ok=True)
    outjson = refs / "havok_layouts.json"
    json.dump(recs, open(outjson, 'w'), indent=1)
    (refs / "dropped_classes.txt").write_text('\n'.join(sorted(dropped)))
    print("parsed %d hk* records -> %s" % (len(recs), outjson))
    withf = sum(1 for v in recs.values() if v['fields'])
    print("  %d have >=1 field; %d are polymorphic" %
          (withf, sum(1 for v in recs.values() if v['vtable'])))


if __name__ == '__main__':
    main()
